### ISSUE TITLE
Port remaining articles from previous design history site

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/bat-design-history#24]
- [x] [Kingston School Direct](/publish-teacher-training-courses/kingston-school-direct)
- [ ] [Iteration - August 15](https://github.com/DFE-Digital/bat-design-history-old/blob/master/app/views/publish-teacher-training/publish-changes/iteration-aug-15.html)
- [x] [Manage applications as launched](https://bat-design-history-old.herokuapp.com/manage-applications/as-launched-26-nov-2019)

2 pages in ‘Publish teacher training courses’, 1 in Manage applications

**Comment by fofr** [comment]
2 added in https://github.com/DFE-Digital/bat-design-history/pull/36
