### ISSUE TITLE
Remove crown, crest and New Transport font

### ISSUE THREAD

**Issue by simonwhatley** [DFE-Digital/bat-design-history#306]
The design history isn't on a GOV.UK domain so should not use the crown and crest logos, nor the New Transport font.

**Comment by paulrobertlloyd** [comment]
This has come up a few times. I was wondering if we could use the patterns that the Home Office has created, which are designed for internal tools: https://design.homeoffice.gov.uk. I did briefly look at this, forget what issues prevented me from continuing.

**Comment by paulrobertlloyd** [comment]
(But yes, in the interim remove the crown and font)

**Comment by fofr** [comment]
Let's get it hosted on `.education.gov.uk`

**Comment by frankieroberto** [comment]
We can close this now as it's hosted on a `*.gov.uk` domain... 🙌

**Comment by paulrobertlloyd** [comment]
Sweet URL! (Though now have to update my UX London slides…)
