### ISSUE TITLE
Images on "Exploring ways to integrate multiple services in the becoming a teacher journey" are returning 404

### ISSUE THREAD

**Issue by michaelgallagher** [DFE-Digital/bat-design-history#989]
the images on this page: 

https://becoming-a-teacher.design-history.education.gov.uk/apply-for-teacher-training/exploring-ways-to-integrate-the-services

... are returning a 404

(sorry, wasn't sure where else to post this!)

**Comment by frankieroberto** [comment]
@michaelgallagher thanks for reporting!  The issue is caused by the missing trailing slash in the URL, it works when this is present: https://becoming-a-teacher.design-history.education.gov.uk/apply-for-teacher-training/exploring-ways-to-integrate-the-services/

I'll look into how to fix this - but can I check where you got that link from? The internal links within the site itself should all be adding the trailing slash.

**Comment by michaelgallagher** [comment]
ah, nice! i'm pretty sure i got the link from the public digital newsletter (in july), as it lacks the trailing slash (see [here](https://us18.campaign-archive.com/?u=267242671076d81909a499704&id=461ab73da5))

**Comment by frankieroberto** [comment]
@michaelgallagher that link seems to have the trailing slash for me?!

Regardless, we should fix (ideally it should redirect to the right URL) - but it's a little tricky to work out how due to the way the site is rendered by Netlify.

**Comment by michaelgallagher** [comment]
@frankieroberto lol maybe the answer is "i'm bad at copying URLs" ?

**Comment by frankieroberto** [comment]
@michaelgallagher it's not your fault - it _should_ work (either redirect or render properly) without the trailing slash!

@paulrobertlloyd I don't suppose you’ve come across this before at all? I think it must be some quirk of how the BAT design history site is set up + deployed to Netlify, as I can't replicate it with newer design histories based on the plugin...

**Comment by paulrobertlloyd** [comment]
I wonder if it’s to do with the redirect to the new `*.design-history.education.gov.uk` domain; [Netlify forces a trailing slash](https://docs.netlify.com/routing/redirects/redirect-options/#trailing-slash), but maybe that gets lost with this redirect? Not sure how much this is governed by the project’s [`netlify.toml`](https://github.com/DFE-Digital/bat-design-history/blob/main/netlify.toml).

As a bit of background, so as to make it easier to reference files saved in the `images` directory, these get copied to the same folder as the generated HTML:

https://github.com/DFE-Digital/bat-design-history/blob/7ad25be1e5f81707a4e65d3fb9766d0c0a0c5f74/.eleventy.js#L38

This then means images can use relative URLs:

`/app/posts/section/my-great-post.md` → `/section/my-great-post/index.html`
`/app/images/section/my-great-post/image.jpg` → `/section/my-great-post/image.jpg`

```markdown
![My great image](image.jpg)
```

Of course, using absolute URLs for images like this falls apart if the trailing slash disappears and the relative root moves up one level 🥴

**Comment by simonwhatley** [comment]
This issue has been fixed by setting pretty URLs to `true`.
